### ISSUE TITLE
How to run your project?

### ISSUE THREAD

**Issue by Nishant5454** [Naveen-Karanamu/Zomato-Full-Stack-Clone#1]

**Comment by Naveen-Karanamu** [comment]
Navigate to the ./client folder and run the command to run the front end:
`npm run start`

Navigate to the ./server folder and run the command to run the back end:
`npm run dev`

ps: 
- Create your own clusters in MongoDB, AWS S3 bucket, Google-O-Auth API, Mailgun API.

** Then create a .env file in your server folder and all the required envirement variables and their  values as follows:

```
MONGO_URL=

GOOGLE_CLIENT_ID=

GOOGLE_CLIENT_SECRET=

AWS_ACCESS_KEY_ID =

AWS_SECRET_ACCESS_KEY=

MAILGUN_API_KEY=

MAILGUN_DOMAIN=
```
